### ISSUE TITLE
[@storybook/testing-react] composeStories typescript error when using parameters.layout

### ISSUE THREAD

**Issue by IanVS** [storybookjs/testing-react#28]
**Describe the bug**

My story is using 

```
parameters: {
    layout: 'fullscreen',
},
```

But I get the typescript error below when I try to `composeStories`:

```
The types of 'parameters.layout' are incompatible between these types.
    Type 'string' is not assignable to type '"fullscreen" | "centered" | "padded" | "none" | undefined'
```

I can work around this by specifying:

```
parameters: {
    layout: 'fullscreen' as const,
},
```

But maybe it's better for the typescript type for composeStories to be a bit more generic and allow `string` (or perhaps specify `readonly` somewhere...)? 

**To Reproduce**
I can create a reproduction if requested, but I think this is pretty straightforward.

**Comment by yannbf** [comment]
Hey @IanVS thanks for raising this issue! I tried to reproduce it in the `example` folder in this codebase but couldn't. What version of Storybook are you using?

**Comment by IanVS** [comment]
I am using `@storybook/react@6.3.0-rc.7`, and `typescript@4.3.2`.  I'll try to reproduce in this repo.

**Comment by IanVS** [comment]
I see that there's an `as Meta` on the default export in the example.  If I remove that coercion (which I think shouldn't be necessary), I get the error I noted above.

**Comment by yannbf** [comment]
Hey @IanVS, sorry for taking so long to reply. I understand the problem now. The thing is, `layout` is a property that does not take `string` as value, it takes `'padded' | 'fullscreen' | 'centered' | 'none'`.

If you have something like this:
```ts
export default {
  ...otherProperties,
  parameters: { layout: 'padded' }
}
```

If you don't define the meta `as Meta`, typescript will complain because it can't be sure that 'padded' won't change to something else.

The error is expected, I believe. The ways to circumvent that are to use `as const`, so that the layout value becomes  _readonly_ and typescript is sure that it's value is always gonna be 'padded':
```ts
export default {
  ...otherProperties,
  parameters: { layout: 'padded' }
} as const
```

or use `as Meta`, which is the recommended way, and gives you pretty good type safety and autocompletion:
```ts
export default {
  ...otherProperties,
  parameters: { layout: 'padded' }
} as Meta
```

I really don't know if it's possible to have this library support proper typings and not be strict about the Meta property.

**Comment by IanVS** [comment]
Alright, yeah that makes sense.  Instead of casting to `Meta`, creating an object of that type and then exporting it seems to give a bit nicer of an error message:

```
const meta: Meta = {
	...otherProperties,
	parameters: {layout: 'padded'},
}
export default meta;
```

The error message when using above with a non-supported layout:

![image](https://user-images.githubusercontent.com/4616705/128930026-511e8a9c-8dd0-4cac-8cb6-9b15f7d4a48a.png)

vs. when casting with `as Meta`:

![image](https://user-images.githubusercontent.com/4616705/128929884-0153e151-4bfe-4610-a0f0-1eea890c5f62.png)
