### ISSUE TITLE
Typing of required fields and default args with composeStories error

### ISSUE THREAD

**Issue by mod-flux** [storybookjs/testing-react#4]
Great library all, really nice to see stories and unit tests coming together.

**Describe the bug**
`composeStories` with default required args cause typing errors, stating that they are missing the required arguments, e.g. `children`. However, when doing so via `composeStory` (as per the example), no errors are present.

**To Reproduce**
1. Run the example provided in `testing-react` repo
2. Move the `Secondary` composed story to the exploded object for `composeStories()` alongisde `Primary`. E.g. `const { Primary, Secondary } = composeStories(stories)`
3. Note that `<Secondary />` without `children` provided, errors. Stating it requires `children`
4. Note that `<Secondary />` did not error when generated with the `composeStory()` function

**Expected behavior**
I would expect `composeStories()` to function as `composeStory()` does but for multiple stories. Default args should be available and automatically picked up, as it is with `composeStory()`.

**Comment by yannbf** [comment]
Hey @mod-flux thanks for opening this issue! This is a known challenge I couldn't figure out how to solve yet, unfortunately :(

The solution for this problem is: 
* composeStories should return stories with type Story<Partial<Props>>

The problem is:
In `composeStories` the type received is a generic which I can't (at least don't know) how to access the props of: 
```ts
composeStories< // type relates to the entire .stories file, including a default export with meta and named exports for stories
  T extends { default: Meta } & { [K in keyof T]: T[K] } // T[K] is equivalent of Story type
>
```

So in that generic `T` I can only get the Story type and not its generic args as well.. so it's not possible to return a Story type with partial args, hence the type checking will be very strict (even though you've set the args in the stories file).

It's pretty annoying, there is a test explaining it [here](https://github.com/storybookjs/testing-react/blob/main/example/src/stories/Button.test.tsx#L34)

For the meantime, the only workaround is to use `composeStory` instead.

Hang tight, I'll keep looking for a solution!

**Comment by mod-flux** [comment]
Thanks for the response @yannbf. Glad to hear it's the roadmap. If I get some time, I will do some testing and see if I can figure something out.

The workaround is fine for now, loving this library, great job!

**Comment by yannbf** [comment]
Hey @mod-flux thanks for your patience! I'm happy to say that a solution was found and you can try it out in version 0.0.7!

huuuuge thanks to @keithlayne for the great help!!

**Comment by mod-flux** [comment]
@yannbf and @keithlayne I can confirm it works a treat, thank you very much! :-)
