### ISSUE TITLE
global decorators receive globals object rather than its value

### ISSUE THREAD

**Issue by zanona** [storybookjs/testing-react#8]
**Describe the bug**
Global decorators have different behaviour on unit testing whereas storybook uses the value as `context.globals.locale` but `testing-react` passes an global object instead of its value.

**Expected behavior**
I would expect that the decorator values on unit testing inherited global values the same as the way storybook does.

```jsx
const LocaleProvider = ({ lang, children }) => {
	console.log(lang);
        return children;
};

// storybook output
'en'

// testing-react output
{
      name: 'Locale',
      description: 'Internationalization locale',
      defaultValue: 'en',
      toolbar: { icon: 'globe', items: [ [Object], [Object] ] }
}

```

```jsx
// .storybook/preview.js
import React from "react";
import LocaleProvider from "/src/components/LocaleProvider";

export const decorators = [
	(Story, context) => (
                {/* react-testing passes entire global object here instead of value*/}
		<LocaleProvider lang={context.globals.locale}>
			<Story {...context} />
		</LocaleProvider>
	),
];

export const globalTypes = {
	locale: {
		name: "Locale",
		description: "Internationalization locale",
		defaultValue: "en",
		toolbar: {
			icon: "globe",
			items: [
				{ value: "en", right: "🇺🇸", title: "English" },
			],
		},
	},
};

```

```jsx
// src/components/NavService.test.jsx
import React from "react";
import { render, act } from "@testing-library/react";
import { composeStories } from "@storybook/testing-react";
import * as stories from "/src/components/NavServices.stories";

const { Services } = composeStories(stories);

it("renders component", async () => {
	const rendered = render(<Services />);
	await act(() => new Promise((resolve) => setTimeout(resolve)));
	//rendered.debug();
	expect(rendered).toBeTruthy();
});

```

**Possible solution**

The workaround I could find is to manually tweak the contents of the locale global on the `setupFile.js` file

```diff
// setupFile.js <-- this will run before the tests in jest.
import { setGlobalConfig } from "@storybook/testing-react";
import * as globalStorybookConfig from "./.storybook/preview"; // path of your preview.js file

+ // manually tweak the value of locale global
+ globalStorybookConfig.globalTypes.locale = globalStorybookConfig.globalTypes.locale.defaultValue;

setGlobalConfig(globalStorybookConfig);
```

Although I can already see the need of customizing these values per test, so some sort of interface to allow this would be welcome such as:

```js
const Story = ComposeStory(story, meta);
Story.globals.locale = 'fr'

it('renders component in french', ...);
```

**Comment by yannbf** [comment]
Hey @zanona thanks a lot for using this library! I believe there's some extra work done via other parts of Storybook (maybe addon toolbars) which process the globals, and currently testing-react only passes down the entire globals object. I will look into it. 

Thanks for raising the issue!

**Comment by yannbf** [comment]
Hey @zanona, thanks to you notifying about this bug, it's fixed and should now behave like Storybook! Please update to version 0.0.9 and let me know if it works for you.

Also like Storybook, the globals are defined once globally, and are only changed via interaction in case you are using addon-toolbars. That kind of interaction wouldn't happen while running your tests. Instead of changing globalTypes midtest, you can compose your stories passing the global types you want in a custom global config object. 

There is an optional parameter in both `composeStory` and `composeStories` of which you can pass your custom global configuration. If you don't pass anything, it will get the one from your preview.js file that you defined in your setup files, otherwise it will just use an empty object. Keep in mind though that it will **override** the globalConfig, so if you want to keep the one from preview + a simple change, you need to merge the objects yourself.

Here's an example on how to achieve that:
```js
// created for easier code reuse
const getGlobalConfig = (language = 'en') => ({
  globalTypes: { locale: { defaultValue: language } },
});


// example with composeStories(stories, globalConfig)
const { Primary, Secondary } = composeStories(stories, getGlobalConfig('fr'));

// example with composeStory(story, meta, globalConfig)
const Secondary = composeStory(stories.Secondary, stories.default, getGlobalConfig('fr'));
```

And if you were to keep the config from preview.js:
```js
import * as originalGlobalConfig from '.././.storybook/preview'
// created for easier code reuse
const getGlobalConfig = (language = 'en') => ({
  ...originalGlobalConfig,
  globalTypes: { 
    ...originalGlobalConfig.globalTypes,
    locale: { defaultValue: language } 
  },
});
```

I also added an example in the [tests](https://github.com/storybookjs/testing-react/blob/main/example/src/stories/Button.test.tsx#L51) for this repo.

I was not sure  if the custom global config should be documented as it can be more confusing and it's easier if people just rely on defaults, but your use case might have changed my perspective. I will think about it and likely update the docs soon!

**Comment by zanona** [comment]
That's great, @yannbf.
Thanks so much for implementing this so quickly. I have just updated to `0.0.9`.
Also, thanks for sharing the recipe for overriding globals, I think that's a nice solution :+1:
